# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://yucayeque.io
title: Yucayeque.io
email: contact@yucayeque.io
author: Jonathan Lozada De La Matta
description: Botanica, NurSery & Engineering.
copyright: 'Copyright &copy; 2021 YUCAYEQUE LLC. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Instagram
    url: https://www.instagram.com/yucayeque_nursery/
  - title: Amazon Store
    url:  https://www.amazon.com/shops/yucayeque_botanica
  - title: Ebay Store
    url: https://www.ebay.com/usr/yucayeque
  #- title: Github
   # url: https://github.com/yucayeque5
  - title: Etsy Store
    url: https://www.etsy.com/shop/Yucayeque
