# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.yucayeque.io
title: Yucayeque.io
email: contact@yucayeque.io
author: Jonathan Lozada De La Matta
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2021 YUCAYEQUE LLC. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://instagram/yucayeque_nursery
  - title: github
    url: https://github.com/yucayeque5
  - title: etsy
    url: https://www.etsy.com/shop/Yucayeque
